blog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url , include
from blog.views import create_user_view , create_user_form ,profile,edit_profile_view,edit_profile_form ,base
from django.contrib.auth.views import LoginView,LogoutView
app_name='blog'
urlpatterns = [
    url(r'^user_view/$',create_user_view,name='create_user_view'),
    url(r'^base/$',base,name='base'),
    url(r'^user_form/$',create_user_form,name='create_user_form'),
    url(r'^profile/$',profile,name='create_profile'),
    url(r'^profile/edit_view/$',edit_profile_view,name='edit_view'),
    url(r'^profile/edit_form/$',edit_profile_form,name='edit_form'),

    url(r'^login/$',LoginView.as_view(template_name='html/login.html'),name='login'),
    url(r'^logout/$',LogoutView.as_view(template_name='html/logout.html'),name='logout'),

]

fb/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url , include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'blog/',include('blog.urls',namespace='blog')),
    url(r'facebook/',include('facebook.urls',namespace='facebook')),
    url(r'tweet/',include('tweet.urls',namespace='tweet')),
]

tweet/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url , include
from tweet.views import tweet_home , pub_tweet ,friend_profile ,change_friend

app_name='tweet'
urlpatterns = [
    url('^tweet_home$',tweet_home,name='tweet_home'),
    url('^tweet_friend/(?P<idd>\d+)/$',friend_profile,name='tweet_friend'),
    url('^change_friend/(?P<operation>.+)/(?P<pk>\d+)/$',change_friend,name='change_friend'),
    url('^tweet_pub$',pub_tweet.as_view(),name='tweet_pub'),
    #url('^testget/$',testhome.get.as_view()),

]

blog/models.py
from django.db import models

from django.contrib.auth.models import User
from django.db.models.signals import  post_save

class User_profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    description=models.CharField(max_length=100,default='')
    city=models.CharField(max_length=20,default=' ')
    website=models.URLField(default='')
    phone=models.IntegerField(default=0)
    def __str__(self):
        return  self.user.username

def create_profile(sender,**kwargs):
    if kwargs['created']:
        USER_profile=User_profile.objects.create(user=kwargs['instance'])


post_save.connect(create_profile , sender=User)

blog/forms.py
from django import forms

from blog.models import User_profile
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django.contrib.auth.models import User


class create_user(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'first_name', 'last_name']


class edit_profile(UserChangeForm):
    class Meta:
        model=User
        fields=['email','first_name','last_name']

blog/views.py
from django.shortcuts import render , redirect
from django.http import  HttpResponse
from blog.forms import create_user ,edit_profile  ,User_profile
from django.contrib.auth.forms import UserCreationForm , UserChangeForm

def base(request):

    return  render(request,'html/base.html')
def create_user_view (request):
    if request.method=='POST':
        form=UserCreationForm(request.POST )
        if form.is_valid():
            form.save()
            return redirect('/blog/base')
    else:
        form = UserCreationForm()
        context={'form':form}
        return render(request, 'html/register_view.html', context)

def create_user_form(request):
    if request.method=='POST':
        form=create_user(request.POST )
        if form.is_valid():
            form.save()
            return redirect('/blog/base')
    else:
        form = create_user()
        context={'form':form}
        return render(request, 'html/register_view.html', context)

    """form=create_user(request.POST or None)
    if form.is_valid():
        form.save()
    context={'form':form}
    return render(request, 'html/register_form.html', context)
"""

def profile(request):
    context={'user':request.user}
    return render(request, 'html/profile.html', context)


def edit_profile_view(request):
    if request.method=='POST':
        form=UserChangeForm(request.POST ,instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('/blog/profile')
    else:
        form=UserChangeForm(instance=request.user)
        context = {'form': form}
        return render(request, 'html/edit_profile_view.html', context)


def edit_profile_form(request):
    if request.method=='POST':
        form=edit_profile(request.POST ,instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('/blog/profile')
    else:
        form=edit_profile(instance=request.user)
        context = {'form': form}
        return render(request, 'html/edit_profile_form.html', context)

blog/templates/html/add_info.html
{%  extends 'html/base.html' %}
{% block add_info %}
    <form action="" method="post">

    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="login">


</form>
      {% endblock %}

blog/templates/html/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.6">
    <title>Top navbar example · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.4/examples/navbar-static/">

    <!-- Bootstrap core CSS -->
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">

    <!-- Favicons -->


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="navbar-top.css" rel="stylesheet">
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
  <a class="navbar-brand" href="#">Top navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
        {% if user.is_authenticated %}

                <li class="nav-item active">
        <a class="nav-link" href="{% url 'blog:create_profile' %}">profile <span class="sr-only">(current)</span></a>
      </li>
        <li class="nav-item active">
        <a class="nav-link" href="{% url 'blog:edit_form' %}">editrpofile <span class="sr-only">(current)</span></a>
      </li>
        <li class="nav-item active">
        <a class="nav-link" href="{% url 'blog:logout' %}">logout <span class="sr-only">(current)</span></a>
      </li>

              <li class="nav-item active">
        <a class="nav-link" href="/facebook/pub/{{ user.id }}">pub_fb <span class="sr-only">(current)</span></a>
      </li>

                    <li class="nav-item active">
        <a class="nav-link" href="{% url 'tweet:tweet_home' %}">tweet home <span class="sr-only">(current)</span></a>
      < <li class="nav-item active">
        <a class="nav-link" href="{% url 'tweet:tweet_pub' %}">tweet pub <span class="sr-only">(current)</span></a>
      </li>


            <li class="nav-item active">
        <a class="nav-link" href="#">add info  <span class="sr-only">(current)</span></a>
      </li>
        {% else %}
            <li class="nav-item active">
        <a class="nav-link" href="{% url 'blog:base' %}">Home <span class="sr-only">(current)</span></a>
      </li>
        <li class="nav-item active">
        <a class="nav-link" href="{% url 'blog:login' %}">login <span class="sr-only">(current)</span></a>
      </li>
        <li class="nav-item active">
        <a class="nav-link" href="{% url 'blog:create_user_form' %}">register <span class="sr-only">(current)</span></a>
      </li>



        {% endif %}

    </ul>
    <form class="form-inline mt-2 mt-md-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

<main role="main" class="container">
  <div class="jumbotron">
   {% block login %}
      {% endblock %}
  {% block register%}
      {% endblock %}
  {% block profile %}
      {% endblock %}
  {% block edit_profile %}
      {% endblock %}

  {% block add_info %}
      {% endblock %}
 {% block pub_fb %}
      {% endblock %}

  {% block tweet_home %}
      {% endblock %}
  {%  block tweet_pub %}
  {% endblock %}
  {%  block tweet_profile %}
  {% endblock %}

  </div>
</main>


  </body>

</html>

blog/templates/html/edit_profile_form.html
{%  extends 'html/base.html' %}
  {% block profile %}
      <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="login">
</form>

      {% endblock %}

blog/templates/html/edit_profile_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="login">
</form>

</body>
</html>

blog/templates/html/login.html
{%  extends 'html/base.html' %}
{% block login %}
    <form action="" method="post">

    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="login">
</form>
      {% endblock %}

blog/templates/html/logout.html
{%  extends 'html/base.html' %}
{%  block logout %}
    <form action="" method="post">

    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="login">
</form>

{% endblock %}

blog/templates/html/profile.html
{%  extends 'html/base.html' %}
{% block profile %}
    <form action="" method="post">

    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="login">
</form>

<h3>name : {{ user.first_name }}</h3><br/>
<h3>username :{{ user.username }}</h3><br/>
<h3>lastname :{{ user.last_name }}</h3><br/>
<h3>password : {{ user.password }}</h3>
<h3>password : {{ user.user_profile.description}}</h3>
<h3>password : {{ user.user_profile.phone }}</h3>


      {% endblock %}

blog/templates/html/register_form.html
{%  extends 'html/base.html' %}
{% block register%}
    <form action="" method="post">

    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="login">
</form>


<br/>
      {% endblock %}

blog/templates/html/register_view.html
{%  extends 'html/base.html' %}


{% block register %}
    <form action="" method="post">

    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="login">
</form>

      {% endblock %}